/**
 * Tencent Mars XLog binary parser.
 *
 * Mars XLog stores records in a custom binary format.  The no-crypt records
 * generated by mars-xlog 1.2.5 look like:
 *   [1 byte  magic]
 *   [2 bytes sequence number (LE)]
 *   [1 byte  begin hour]
 *   [1 byte  end hour]
 *   [4 bytes payload length (LE)]
 *   [64 bytes config/public-key slot]
 *   [payload]
 *   [1 byte  0x00 record terminator]
 *
 * In no-crypt logs, magic 0x09 contains raw-deflate payload and magic 0x08
 * contains plain text payload such as mmap begin/end markers.
 *
 * After decompression each block contains log entries separated by null
 * bytes, typically in the format:
 *   YYYY-MM-DD HH:MM:SS.ms V|pid,tid|tag|message
 */

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const LEGACY_HEADER_SIZE = 5 // magic(1) + seq(2) + beginHour(1) + endHour(1)
const MARS_RECORD_HEADER_SIZE = 73 // legacy header + len(4) + config/public key(64)

const MAGIC_NO_CRYPT_ZLIB = 0x03
const MAGIC_CRYPT_ZLIB = 0x04
const MAGIC_NO_CRYPT_ZSTD = 0x05
const MAGIC_CRYPT_ZSTD = 0x06
const MAGIC_NO_CRYPT_ZLIB_V2 = 0x07
const MAGIC_MARS_PLAIN_NO_CRYPT = 0x08
const MAGIC_MARS_COMPRESSED_NO_CRYPT = 0x09

/** Recognised xlog magic bytes. */
const XLOG_MAGICS = new Set<number>([
  MAGIC_NO_CRYPT_ZLIB,
  MAGIC_CRYPT_ZLIB,
  MAGIC_NO_CRYPT_ZSTD,
  MAGIC_CRYPT_ZSTD,
  MAGIC_NO_CRYPT_ZLIB_V2,
  MAGIC_MARS_PLAIN_NO_CRYPT,
  MAGIC_MARS_COMPRESSED_NO_CRYPT,
])

/** Magic bytes that indicate the body is zstd-compressed. */
const ZSTD_MAGICS = new Set<number>([
  MAGIC_NO_CRYPT_ZSTD,
  MAGIC_CRYPT_ZSTD,
])

/** Magic bytes that indicate the body is TEA-encrypted. */
const CRYPT_MAGICS = new Set<number>([MAGIC_CRYPT_ZLIB, MAGIC_CRYPT_ZSTD])

const MARS_NO_CRYPT_MAGICS = new Set<number>([
  MAGIC_MARS_PLAIN_NO_CRYPT,
  MAGIC_MARS_COMPRESSED_NO_CRYPT,
])

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

/** Quick check – does the buffer *look* like an xlog file? */
export function isXLogByMagic(bytes: Uint8Array): boolean {
  if (bytes.length < 1) return false
  return XLOG_MAGICS.has(bytes[0])
}

/** Check whether a path has a known xlog extension. */
const XLOG_EXTENSIONS = new Set(['xlog', 'xlog2', 'mars'])

export function isXLogByExtension(path: string): boolean {
  const ext = path.split('.').pop()?.toLowerCase() ?? ''
  return XLOG_EXTENSIONS.has(ext)
}

/**
 * Parse a Mars XLog buffer into human-readable text.
 *
 * @param data  Raw xlog file bytes (ArrayBuffer or Uint8Array).
 * @param cryptKey  Optional 16-byte TEA key for encrypted logs.
 * @returns Decoded log text with one line per entry.
 */
export async function parseXLog(
  data: ArrayBuffer | Uint8Array,
  cryptKey?: Uint8Array,
): Promise<string> {
  const bytes = data instanceof Uint8Array ? data : new Uint8Array(data)

  if (bytes.length < LEGACY_HEADER_SIZE) {
    throw new Error('文件太小，不是有效的 xlog 格式')
  }

  const magic = bytes[0]
  if (!XLOG_MAGICS.has(magic)) {
    throw new Error(`未识别的 xlog magic 字节: 0x${magic.toString(16)}`)
  }

  if (ZSTD_MAGICS.has(magic)) {
    throw new Error('Zstd 压缩的 xlog 暂不支持')
  }

  if (MARS_NO_CRYPT_MAGICS.has(magic)) {
    return parseMarsNoCryptXLog(bytes)
  }

  const hasCrypt = CRYPT_MAGICS.has(magic)

  // Compatibility for the synthetic legacy fixtures used by this project.
  const body = bytes.slice(LEGACY_HEADER_SIZE)
  const lines: string[] = []
  let pos = 0
  let blockCount = 0
  let failCount = 0
  let lastError = ''

  while (pos + 2 <= body.length) {
    const blockLen = body[pos] | (body[pos + 1] << 8) // uint16 LE
    pos += 2

    if (blockLen === 0) {
      // Zero-length block signals end-of-stream in some versions.
      break
    }

    if (pos + blockLen > body.length) {
      // Truncated block – stop gracefully.
      break
    }

    blockCount++
    let compressed = body.slice(pos, pos + blockLen) as Uint8Array<ArrayBuffer>
    pos += blockLen

    // Decrypt if needed.
    if (hasCrypt) {
      if (cryptKey && cryptKey.length >= 16) {
        compressed = teaDecrypt(compressed, cryptKey)
      } else {
        // Try with an all-zero key as a best-effort fallback.
        compressed = teaDecrypt(compressed, new Uint8Array(16))
      }
    }

    // Decompress the block.
    try {
      const decompressed = await inflateZlib(compressed)
      const text = new TextDecoder('utf-8', { fatal: false }).decode(decompressed)
      // Split on null bytes – each entry is null-terminated.
      for (const entry of text.split('\0')) {
        const trimmed = entry.trim()
        if (trimmed.length > 0) {
          lines.push(trimmed)
        }
      }
    } catch (err) {
      failCount++
      lastError = err instanceof Error ? err.message : String(err)
    }
  }

  if (lines.length === 0) {
    const parts = [`xlog 解析未产生任何日志行`]
    parts.push(`文件大小: ${formatBytes(bytes.length)}`)
    parts.push(`Magic: 0x${magic.toString(16)}${hasCrypt ? ' (加密)' : ''}`)
    parts.push(`数据块: ${blockCount} 个`)
    if (failCount > 0) {
      parts.push(`解压失败: ${failCount} 个${lastError ? ` (${lastError})` : ''}`)
    }
    parts.push(`请检查文件是否损坏或使用了未知的加密密钥`)
    throw new Error(parts.join('，'))
  }

  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Mars 1.2.5 no-crypt record parser (magic 0x08 / 0x09)
// ---------------------------------------------------------------------------

async function parseMarsNoCryptXLog(bytes: Uint8Array): Promise<string> {
  const lines: string[] = []
  let pos = 0
  let recordCount = 0
  let failCount = 0
  let lastError = ''

  while (pos < bytes.length) {
    const magic = bytes[pos]

    if (magic === 0x00) {
      pos++
      continue
    }

    if (!MARS_NO_CRYPT_MAGICS.has(magic)) {
      if (lines.length > 0) break
      throw new Error(`未识别的 xlog magic 字节: 0x${magic.toString(16)}`)
    }

    if (pos + MARS_RECORD_HEADER_SIZE > bytes.length) {
      break
    }

    const payloadLength = readUInt32LE(bytes, pos + 5)
    const payloadStart = pos + MARS_RECORD_HEADER_SIZE
    const payloadEnd = payloadStart + payloadLength

    if (payloadEnd > bytes.length) {
      break
    }

    recordCount++
    const payload = bytes.slice(payloadStart, payloadEnd) as Uint8Array<ArrayBuffer>

    try {
      const text =
        magic === MAGIC_MARS_COMPRESSED_NO_CRYPT
          ? decodeText(await inflateRawDeflate(payload))
          : decodeText(payload)
      pushDecodedEntries(lines, text)
    } catch (err) {
      failCount++
      lastError = err instanceof Error ? err.message : String(err)
    }

    pos = payloadEnd
    if (bytes[pos] === 0x00) {
      pos++
    }
  }

  if (lines.length === 0) {
    const parts = [`xlog 解析未产生任何日志行`]
    parts.push(`文件大小: ${formatBytes(bytes.length)}`)
    parts.push(`数据记录: ${recordCount} 个`)
    if (failCount > 0) {
      parts.push(`解码失败: ${failCount} 个${lastError ? ` (${lastError})` : ''}`)
    }
    parts.push(`请检查文件是否损坏或是否为加密 xlog`)
    throw new Error(parts.join('，'))
  }

  return lines.join('\n')
}

function decodeText(data: Uint8Array): string {
  return new TextDecoder('utf-8', { fatal: false }).decode(data)
}

function readUInt32LE(bytes: Uint8Array, offset: number): number {
  return (
    (bytes[offset] |
      (bytes[offset + 1] << 8) |
      (bytes[offset + 2] << 16) |
      (bytes[offset + 3] << 24)) >>>
    0
  )
}

function pushDecodedEntries(lines: string[], text: string): void {
  for (const entry of text.split(/\0|\r\n|\r|\n/)) {
    const trimmed = entry.trim()
    if (trimmed.length > 0) {
      lines.push(trimmed)
    }
  }
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Decompress a zlib (deflate) buffer using the browser's native
 * DecompressionStream.  Falls back to raw-deflate if the zlib header is
 * missing.
 */
async function inflateZlib(data: Uint8Array<ArrayBuffer>): Promise<Uint8Array<ArrayBuffer>> {
  // Try standard zlib-wrapped deflate first.
  try {
    return await decompressStream(data, 'deflate')
  } catch {
    // Some xlog implementations write raw deflate (no zlib header).
  }

  return decompressStream(data, 'deflate-raw')
}

function inflateRawDeflate(
  data: Uint8Array<ArrayBuffer>,
): Promise<Uint8Array<ArrayBuffer>> {
  return decompressStream(data, 'deflate-raw', { allowPartial: true })
}

async function decompressStream(
  data: Uint8Array<ArrayBuffer>,
  format: CompressionFormat,
  options: { allowPartial?: boolean } = {},
): Promise<Uint8Array<ArrayBuffer>> {
  const ds = new DecompressionStream(format)
  const writer = ds.writable.getWriter()
  const reader = ds.readable.getReader()

  // Write and close in parallel with reading.
  let writeError: unknown
  let readError: unknown
  const writePromise = writer
    .write(data)
    .then(() => writer.close())
    .catch((error) => {
      writeError = error
    })

  const chunks: Uint8Array[] = []
  try {
    while (true) {
      const { done, value } = await reader.read()
      if (done) break
      chunks.push(value)
    }
  } catch (error) {
    readError = error
  }

  await writePromise

  if ((readError || writeError) && (!options.allowPartial || chunks.length === 0)) {
    throw readError ?? writeError
  }

  // Concatenate chunks.
  const totalLen = chunks.reduce((sum, c) => sum + c.length, 0)
  const result = new Uint8Array(totalLen)
  let offset = 0
  for (const chunk of chunks) {
    result.set(chunk, offset)
    offset += chunk.length
  }

  return result
}

// ---------------------------------------------------------------------------
// TEA (Tiny Encryption Algorithm) – Mars-compatible variant
// ---------------------------------------------------------------------------

/**
 * Decrypt a buffer using the Mars TEA variant.
 *
 * Mars uses a 16-round TEA in CBC-like mode where each 8-byte block is
 * XOR'd with the previous ciphertext block before decryption.  The IV is
 * all-zeros.
 */
function teaDecrypt(data: Uint8Array, key: Uint8Array): Uint8Array<ArrayBuffer> {
  if (data.length < 8 || data.length % 8 !== 0) {
    // Data not aligned to 8 bytes – return as-is (best-effort).
    return data as Uint8Array<ArrayBuffer>
  }

  const k = keyToUint32(key)
  const out = new Uint8Array(new ArrayBuffer(data.length))
  const view = new DataView(out.buffer as ArrayBuffer)
  const src = new DataView(data.buffer as ArrayBuffer, data.byteOffset, data.byteLength)

  let prev0 = 0
  let prev1 = 0

  for (let i = 0; i < data.length; i += 8) {
    let v0 = src.getUint32(i, true)
    let v1 = src.getUint32(i + 4, true)

    // Save ciphertext for CBC XOR.
    const ct0 = v0
    const ct1 = v1

    // 16-round TEA decrypt.
    const delta = 0x9e3779b9
    let sum = (delta * 16) >>> 0

    for (let r = 0; r < 16; r++) {
      v1 = (v1 - (((v0 << 4) + k[2]) ^ (v0 + sum) ^ ((v0 >>> 5) + k[3]))) >>> 0
      v0 = (v0 - (((v1 << 4) + k[0]) ^ (v1 + sum) ^ ((v1 >>> 5) + k[1]))) >>> 0
      sum = (sum - delta) >>> 0
    }

    // CBC: XOR with previous ciphertext.
    v0 ^= prev0
    v1 ^= prev1

    view.setUint32(i, v0, true)
    view.setUint32(i + 4, v1, true)

    prev0 = ct0
    prev1 = ct1
  }

  return out
}

/** Convert a 16-byte key to 4 uint32 values (little-endian). */
function keyToUint32(key: Uint8Array): [number, number, number, number] {
  const view = new DataView(key.buffer as ArrayBuffer, key.byteOffset, key.byteLength)
  return [
    view.getUint32(0, true),
    view.getUint32(4, true),
    view.getUint32(8, true),
    view.getUint32(12, true),
  ]
}
